apiVersion: batch/v1
kind: Job
metadata:
  name: VAR_POD_NAME
  labels:
    app: k8-align
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
        - name: VAR_POD_NAME
          image: DOCKER_IMAGE
          imagePullPolicy: Always
          args: [
              "FASTQ_INPUT",
              "REF_GENOME",
              "UNDEDUPLICATED_OUTPUT",
              "NON_UMI_AWARE_DEDUPLICATED_OUTPUT",
              "UMI_AWARE_DEDUPLICATED_OUTPUT",
          ]
      imagePullSecrets:
        - name: container-registry-reader
      restartPolicy: Never
