#!/usr/bin/env bash

REPO_DIR_NAME="$(dirname "$0")" || exit 1
SCRIPT_NAME="$(basename "$0")" || exit 1

print_usage(){
  echo "USAGE: $0 run"
  echo "USAGE: $0 build --name <image-name>"
  echo "USAGE: $0 push --name <image-name>"
  echo "USAGE: $0 version"
  echo "  <image-name> Name of the Docker image"
  exit 1
}

print_build_usage(){
  echo "Build new Docker image"
  echo "USAGE: $0 build --name <image-name>"
  echo "  [-n/--name] Name of the Docker image (Required)"
  exit 1
}

print_push_usage(){
  echo "Push Docker image to GCP. If name-version combination exists, please rebuilt and push with new name."
  echo "USAGE: $0 push --name <image-name>"
  echo "  [-n/--name] Name of the Docker image (Required)"
  exit 1
}

main() {
  if [ $# -lt 1 ]; then
   print_usage
  fi

  local CMD=$1 && shift
  case $CMD in
  build)
     build "$@"
     ;;
  push)
     push "$@"
     ;;
  run)
     run "$@"
     ;;
  version)
     version "$@"
     ;;
  *)
     print_usage
     ;;
  esac
}

build() {
  local UNRECOGNIZED=()
  local key
  while [[ $# -gt 0 ]]
  do
    key="$1" && shift
    case $key in
      -n|--name)
        name="$1" && shift;;
      *)
        UNRECOGNIZED+=("${key}");;
    esac
  done
  
  # sanity checks
  local input_error=false
  if [[ ! ${#UNRECOGNIZED[@]} -eq 0 ]]; then
    print_error_msg "Unrecognized options to ${SCRIPT_NAME}: options=(${UNRECOGNIZED[*]})"
    input_error=true
  fi
  if [[ -z ${name} ]]; then
    print_error_msg "Variable 'name' has not been set"
    input_error=true
  fi
  if [[ ${input_error} == true ]]; then
    print_build_usage
  fi

  docker build "${REPO_DIR_NAME}" -t "${name}" || die "Failed Docker build"

  echo "The build has succeeded."
  echo "If you want to push this image to GCP, run the following command:"
  echo "$0 push --name ${name}"
}

push() {
  local UNRECOGNIZED=()
  local key
  while [[ $# -gt 0 ]]
  do
    key="$1" && shift
    case $key in
      -n|--name)
        name="$1" && shift;;
      *)
        UNRECOGNIZED+=("${key}");;
    esac
  done

  # sanity checks
  local input_error=false
  if [[ ! ${#UNRECOGNIZED[@]} -eq 0 ]]; then
    print_error_msg "Unrecognized options to ${SCRIPT_NAME}: options=(${UNRECOGNIZED[*]})"
    input_error=true
  fi
  if [[ -z ${name} ]]; then
    print_error_msg "Variable 'name' has not been set"
    input_error=true
  fi
  if [[ ${input_error} == true ]]; then
    print_push_usage
  fi

  echo "Checking whether image with name '${name}' already exists at GCP"
  already_pushed=$(image_has_already_been_pushed "${name}")

  if [[ ${already_pushed} ]]; then
    die "Image with ${name} has already been pushed to GCP. Please rebuild with a newer version of the image name.'"
  else
    echo "Pushing new image ${name} to GCP"
    docker push "${name}" || die "Failed Docker push"
    echo "Pushed new image ${name} to GCP"
  fi
}

run() {
  local pod_name
  pod_name="$(echo "k8-align-test" | awk '{print tolower($0)}')"
  local clean_pod_name
  clean_pod_name="$(echo "${pod_name}" | tr '_' '-' | tr '[:upper:]' '[:lower:]' | tr '.' '-')"
  local docker_image
  docker_image="$(get_default_docker_image_at_k8)" || die "Could not find default docker image name"

  # Make sure correct credentials are available
  gcloud container clusters get-credentials rerun-cluster --region europe-west4 --project hmf-crunch \
        || die "Could not find credentials at gcp"

  sed \
  -e "s/VAR_POD_NAME/${clean_pod_name}/g" \
  -e "s#DOCKER_IMAGE#${docker_image}#g" \
  "${REPO_DIR_NAME}/k8/hmf-crunch/deploy.yaml" \
  | kubectl create -f -  # use # as separator to handle / in docker image name
}

version() {
  local default_docker_image
  default_docker_image="$(get_default_docker_image_at_k8)" || die "Could not find default docker image name"
  echo "Current default Docker image version at k8: ${default_docker_image}"
}

get_default_docker_image_at_k8() {
  cat "${REPO_DIR_NAME}/default_docker_image_at_k8.txt"
}

image_has_already_been_pushed() {
  local name=$1 && shift
  [[ -n ${name} ]] || die "Not enough arguments to ${FUNCNAME[0]}"
  docker manifest inspect "${name}" > /dev/null 2>&1
}

die() {
  print_error_msg "$1"
  exit 1
}

print_error_msg() {
  echo "[ERROR] $1"
}

main "$@"