#!/usr/bin/env bash

DEPLOYED_DOCKER_IMAGE="eu.gcr.io/hmf-build/k8-align:0.1"

function printUsage(){
    echo "USAGE: $0 run"
    exit 1
}

function main() {
    if [ $# -lt 1 ]; then  # TODO: bump this back up if there are actual arguments
     printUsage
    fi

    CMD=$1 && shift

    case $CMD in
    run)
       run "$@"
       ;;
    *)
       printUsage
       ;;
    esac
}

function run() {
    pod_name="$(echo "k8-align-test" | awk '{print tolower($0)}')"
    clean_pod_name="$(echo "${pod_name}" | tr '_' '-' | tr '[:upper:]' '[:lower:]' | tr '.' '-')"

    # Make sure correct credentials are available
    gcloud container clusters get-credentials rerun-cluster --region europe-west4 --project hmf-crunch || exit 1

    sed \
    -e "s/VAR_POD_NAME/${clean_pod_name}/g" \
    -e "s#DEPLOYED_DOCKER_IMAGE#${DEPLOYED_DOCKER_IMAGE}#g" \
    k8/hmf-crunch/deploy.yaml \
    | kubectl create -f -  # use # as separator to handle / in docker image name
}

main "$@"